import PDFDocument from "pdfkit";
import { Response } from "express";

// Define a palette for consistent branding (Aurora Theme)
const COLORS = {
  primary: "#4F46E5", // Indigo
  textMain: "#1F2937", // Dark Grey
  textLight: "#6B7280", // Light Grey
  success: "#10B981", // Emerald Green
  error: "#EF4444", // Red
  background: "#F3F4F6", // Very light grey
  white: "#FFFFFF",
};

export const generateAttemptPDF = (attempt: any, res: Response) => {
  const doc = new PDFDocument({ margin: 50, size: "A4" });

  // -- HTTP Headers --
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader(
    "Content-Disposition",
    `attachment; filename=attempt-${attempt._id}.pdf`
  );

  doc.pipe(res);

  // -- 1. HEADER SECTION --
  doc
    .rect(0, 0, doc.page.width, 100)
    .fill(COLORS.primary);

  // Logo/Title Text (White on Blue)
  doc
    .fontSize(24)
    .fillColor(COLORS.white)
    .text("AURORA", 50, 35, { characterSpacing: 2 });
    
  doc
    .fontSize(10)
    .text("QUIZ SYSTEM", 50, 60, { characterSpacing: 1 });

  // Report Title (Right aligned in header)
  doc
    .fontSize(20)
    .text("Attempt Report", 0, 35, { align: "right", width: 545 }); // 595 is A4 width - 50 margin

  // Reset Fill Color for body
  doc.fillColor(COLORS.textMain);


  // -- 2. SCORE CARD SECTION --
  const totalQuestions = attempt.responses.length;
  const percentage = Math.round((attempt.score / totalQuestions) * 100);
  
  const scoreColor = percentage >= 50 ? COLORS.success : COLORS.error;
  const scoreY = 130;

  // Draw Score Box
  doc
    .roundedRect(400, scoreY, 150, 80, 5) // x, y, w, h, radius
    .fillAndStroke(COLORS.background, COLORS.textLight);

  doc
    .fillColor(COLORS.textLight)
    .fontSize(10)
    .text("TOTAL SCORE", 400, scoreY + 15, { align: "center", width: 150 });

  doc
    .fillColor(scoreColor)
    .fontSize(28)
    .text(`${percentage}%`, 400, scoreY + 35, { align: "center", width: 150 });


  // -- 3. STUDENT & QUIZ DETAILS (Left Side) --
  let infoY = 130;
  const labelX = 50;
  const valueX = 140;
  const lineHeight = 20;

  // Helper to draw row
  const drawInfoRow = (label: string, value: string) => {
    doc.fontSize(10).fillColor(COLORS.textLight).text(label, labelX, infoY);
    doc.fontSize(10).fillColor(COLORS.textMain).text(value, valueX, infoY);
    infoY += lineHeight;
  };

  // Safe check for populated fields
  const studentName = attempt.student?.name || "Unknown Student";
  const studentEmail = attempt.student?.email || "N/A";
  const quizTitle = attempt.quizRoom?.quiz?.title || "Unknown Quiz";

  drawInfoRow("Student:", studentName);
  drawInfoRow("Email:", studentEmail);
  drawInfoRow("Quiz Title:", quizTitle);
  drawInfoRow("Attempt #:", attempt.attemptNumber.toString());
  drawInfoRow("Submitted:", new Date(attempt.submittedAt).toLocaleString());


  // -- 4. QUESTIONS TABLE --
  let currentY = 240; // Start below the info section

  // Section Header
  doc
    .moveTo(50, currentY)
    .lineTo(550, currentY)
    .strokeColor(COLORS.background)
    .stroke();
  
  currentY += 20;
  doc
    .fontSize(14)
    .fillColor(COLORS.primary)
    .text("Response Detail", 50, currentY);
  
  currentY += 30;

  // Table Header
  doc.fontSize(10).fillColor(COLORS.textLight);
  doc.text("#", 50, currentY);
  doc.text("Question ID / Answer", 80, currentY);
  doc.text("Status", 450, currentY);
  
  currentY += 20;

  // Render Rows
  attempt.responses.forEach((r: any, index: number) => {
    // Check for page break
    if (currentY > 750) {
      doc.addPage();
      currentY = 50;
    }

    // Zebra Striping (Light grey background for even rows)
    if (index % 2 === 0) {
      doc
        .rect(50, currentY - 5, 500, 25)
        .fill(COLORS.background);
    }

    // Row Content
    doc.fillColor(COLORS.textMain).fontSize(10);
    
    // 1. Index
    doc.text((index + 1).toString(), 55, currentY);

    // 2. Selection
    const questionText = `QID: ${r.question.toString().substring(0, 10)}...`; 
    doc.text(questionText, 80, currentY, { width: 300, lineBreak: false });
    
    doc.fontSize(9).fillColor(COLORS.textLight).text(`Selected: ${r.selected}`, 80, currentY + 12);

    // 3. Status (Icon + Text)
    const isCorrect = r.correct;
    doc.fillColor(isCorrect ? COLORS.success : COLORS.error);
    doc.fontSize(10);
    doc.text(isCorrect ? "Correct" : "Incorrect", 450, currentY);

    currentY += 35; // Move down for next row
  });

  // -- 5. FOOTER --
  const pageCount = doc.bufferedPageRange().count;
  for (let i = 0; i < pageCount; i++) {
    doc.switchToPage(i);
    doc
        .fontSize(8)
        .fillColor(COLORS.textLight)
        .text(
            `Generated by Aurora Quiz System | Page ${i + 1} of ${pageCount}`,
            50,
            doc.page.height - 50,
            { align: "center", width: 500 }
        );
  }

  doc.end();
};