import PDFDocument from "pdfkit";
import { Response } from "express";

export const generateAttemptPDF = (
  attempt: any,
  res: Response
) => {
  const doc = new PDFDocument({ margin: 50 });

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader(
    "Content-Disposition",
    `attachment; filename=attempt-${attempt._id}.pdf`
  );

  doc.pipe(res);

  doc
    .fontSize(20)
    .text("Quiz Attempt Report", { align: "center" })
    .moveDown();

  doc.fontSize(12);
  doc.text(`Student: ${attempt.student.name}`);
  doc.text(`Email: ${attempt.student.email}`);
  doc.text(`Quiz: ${attempt.quizRoom.quiz.title}`);
  doc.text(`Attempt #: ${attempt.attemptNumber}`);
  doc.text(
    `Score: ${attempt.score} / ${attempt.responses.length}`
  );
  doc.text(
    `Submitted At: ${new Date(
      attempt.submittedAt
    ).toLocaleString()}`
  );

  doc.moveDown();

  doc
    .fontSize(14)
    .text("Question Summary", { underline: true })
    .moveDown(0.5);

  attempt.responses.forEach((r: any, index: number) => {
    doc
      .fontSize(11)
      .text(
        `${index + 1}. Selected: ${r.selected} | ${
          r.correct ? "✔ Correct" : "✘ Incorrect"
        }`
      );
  });

  doc.moveDown();

  doc
    .fontSize(10)
    .text("Generated by Aurora Quiz System", {
      align: "center",
    });

  doc.end();
};
